spacelift-io/terraform-provider-spacelift

- Dockerfile
This will allow copying the provider binary to an arbitrary Docker image used by customers.
> Build the provider statically

- Dockerfile
- README.md
- spacelift/data_stack.go
- spacelift/e2e/stack_aws_role_test.go
- spacelift/e2e/stack_test.go
- spacelift/resource_stack.go
- spacelift/structs/stack.go
- spacelift/structs/stack_input.go
Given that access is now more flexibly managed by stack access policies, there's no longer any need to handle it using GitHub teams.
> Remove access management

- README.md
- spacelift/resource_mounted_file.go
Just a documentation fix, we've long been using the new mount path and missed some docs
> Fix documentation for file mount path

- spacelift/resource_stack.go
Once the Terraform version is set on the Stack, the lack of this setting should not cause the provider to explicitly nullify it.
> Once the version is set, do not unset

- README.md
- spacelift/data_stack.go
- spacelift/data_stack_test.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
When the version is supplied externally, the entire block gets removed.
> Forget the `terraform` block, just make it work with the new API

- README.md
- spacelift/resource_policy_attachment.go
- spacelift/resource_policy_attachment_test.go
This feature is confusing, and unused. Folks prefer to use stack labels.
> Remove policy custom input

- spacelift/resource_webhook.go
This change updates the secret attribute of the webhook resource to be marked as Sensitive, which will prevent the secret value from being visible during a plan/apply.
> Update the secret attribute of the webhook resource to be marked as sensitive

- spacelift/resource_policy.go
Current error can be confusing if one resource block is responsible for
generating many policies (eg for_each, or module).
```
│ Error: could not create policy: policy name must be unique within one account
│ 
│   on file.tf line 25, in resource "spacelift_policy" "default":
│   25: resource "spacelift_policy" "default" {
```
> Name policy in creation failure message

- .github/workflows/registry-preprod.yml
- .github/workflows/registry-prod.yml
The openssl dependency was missing, which was causing the deployment pipelines to fail silently and be unable to generate a checksum.
> Fix [#1]()
> Add missing openssl dependency

- Dockerfile
It adds the latest aws-cli version 1. Unfortunately, version 2 is still not supported on Alpine images.
```
/ $ aws --version
aws-cli/1.19.93 Python/3.9.5 Linux/5.12.9-200.fc33.x86_64 botocore/1.20.93
```
> Add aws-cli and bump Alpine version

- Dockerfile
This includes a fix to remove a warning about not being able to sync the usage file when the `--sync-usage-file` flag hasn't been specified:
> Update Infracost to 0.9.2

- .github/pull_request_template.md
I keep on forgetting to set the target branch of this repo to `future` when creating PRs that I want to go into preprod first, so adding to the template.
> Add info about target branch to PR template

- spacelift/resource_aws_role.go
- spacelift/resource_context_attachment.go
- spacelift/resource_environment_variable.go
- spacelift/resource_gcp_service_account.go
- spacelift/resource_mounted_file.go
- spacelift/resource_policy_attachment.go
- spacelift/resource_webhook.go
- spacelift/verify_project.go
When a resource can be attached to either a stack or a module, validate the existence to prevent creating a resource for the wrong entity.
> Verify stack and module existence on some creations

- docs/resources/stack.md
- spacelift/resource_stack.go
Sometimes the state file is too large, and importing by path is way more convenient.
> Allow importing state files by path

- docs/resources/stack.md
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
With this change, we allow users to set the slug for the stack. This only works on creation, so there's no use in reading it back, and any attempt to change it after creation will trigger stack recreation.
> Support setting custom slug for a stack

- docs/data-sources/stack_aws_role.md
- docs/data-sources/stack_gcp_service_account.md
- docs/resources/aws_role.md
- docs/resources/azure_integration.md
- docs/resources/azure_integration_attachment.md
- docs/resources/context.md
- docs/resources/context_attachment.md
- docs/resources/drift_detection.md
- docs/resources/environment_variable.md
- docs/resources/gcp_service_account.md
- docs/resources/module.md
- docs/resources/mounted_file.md
- docs/resources/policy.md
- docs/resources/policy_attachment.md
- docs/resources/stack.md
- docs/resources/stack_aws_role.md
- docs/resources/stack_gcp_service_account.md
- docs/resources/vcs_agent_pool.md
- docs/resources/webhook.md
- docs/resources/worker_pool.md
- examples/resources/spacelift_gcp_service_account/resource.tf
- examples/resources/spacelift_module/resource.tf
- Regenerating the docs to get the latest updates on importing and deprecations from @jmfontaine.
- Fixing a typo reported by @kamsz in https://github.com/spacelift-io/terraform-provider-spacelift/pull/267 with the `gcp_service_account` resource docs.
> Regenerate docs and include GCP docs fix

- docs/resources/aws_integration.md
- docs/resources/aws_integration_attachment.md
- spacelift/resource_aws_integration.go
- spacelift/resource_aws_integration_attachment.go
Adding a note to the resources indicating that users should continue to use `spacelift_aws_role` until the new attachments support is rolled out to all users.
> Mark new AWS resources as experimental

- .github/workflows/test-prod.yml
- .github/workflows/test.yml
We're seeing occasional test failures caused by the `terraform` binary being modified while we're trying to execute it as part of the acceptance tests (see this related issue: https://github.com/hashicorp/terraform-plugin-sdk/issues/629).
The suggested solution in the Terraform plugin developer docs is to install a version of Terraform before running `go test`, which should stop the tests from trying to download Terraform themselves.
> Install Terraform before running tests

- docs/resources/space.md
- spacelift/resource_space.go
The `spacelift_space.parent_space_id` is marked as optional but a value is actually required:
Instead of marking it as required, I chose to default to adding spaces to the root by using `root` as default. I found in [the tests for the resource type](https://github.com/spacelift-io/terraform-provider-spacelift/blob/main/spacelift/resource_space_test.go#L23). It works fine and I think that this was the intended behavior.
None
> Add default value for parent space ID

- docs/data-sources/stack.md
- docs/resources/stack.md
- examples/resources/spacelift_stack/resource.tf
- spacelift/data_stack.go
- spacelift/data_stack_test.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
- spacelift/type_conversions.go
This comit enables the ability to set smart sanitization on terraform based stacks.
If the stack uses terraform version 1.0.1 or above, spacelift will sanitize the data output from
`terraform plan` and `terraform apply` using the sensitive field values provided by terraform.
> Add smart sanitization field to stack resources

- spacelift/data_space_test.go
- spacelift/resource_space_test.go
The space ID was changed from `$space_name` to `$space_ulid-$space_name`
> Fix spaces tests

- docs/data-sources/worker_pool.md
- examples/data-sources/spacelift_worker_pool/data-source.tf
Use an actual ID instead of the slug in the example.
> Fix worker_pool datasource example

- spacelift/data_current_space.go
When running in a non-administrative stack this data source cannot be accessed, but error message is not so clear.
> Better error message when using spacelift_current_space

- spacelift/internal/error.go
- spacelift/resource_space.go
Improved error messaging to indicate errors due to stacks being in wrong spaces.
> Mention spaces in error messages

- spacelift/internal/structs/stack_dependency.go
- spacelift/resource_stack_dependency.go
We have modified the backend API and deprecated two fields (`StackID`, `DependsOnStackID`). Let's not use those fields anymore.
> Remove deprecated field from StackDependency API

- docs/data-sources/stack.md
- docs/resources/stack.md
- spacelift/data_stack.go
- spacelift/data_stack_test.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Support for after-run hooks

- docs/resources/stack.md
- spacelift/resource_stack.go
> Refer to allow run promotion in the github_action_deploy description

- spacelift/internal/structs/stack.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
The terraform import handling for stacks was reusing the `resourceStackRead()` function, which sets the ID to an empty string if no stack is found. To solve this I've pulled out query for a stack and updating the state based on a stack struct into separate functions, and I've updated the import handling to detect when the stack can't be found an output a decent error message.
I pulled the `PopulateStack()` function into the structs package to follow the pattern we've taken for the scheduled task structs.
- Fixes [#405](https://github.com/spacelift-io/terraform-provider-spacelift/issues/405)
> Better error message when importing missing stack

- docs/data-sources/space_by_path.md
- spacelift/data_space_by_path.go
- spacelift/data_space_by_path_test.go
- remove `space_id` field from `data_space_by_path`
- fix validation of the path prefix
- add disclaimer to description of `data_space_by_path`
> Fix data space by path

- docs/data-sources/stack.md
- docs/data-sources/stacks.md
- docs/resources/stack.md
- examples/resources/spacelift_stack/resource.tf
- spacelift/data_stack.go
- spacelift/data_stack_test.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
Adds kubectl version to Kubernetes backend configuration.
> Add kubectl version

- docs/resources/module.md
- docs/resources/stack.md
- spacelift/resource_module.go
- spacelift/resource_stack.go
Self-hosting instances don't have a concept of a default worker pool, so the worker pool always needs to be specified for stacks and modules.
> Clarify worker_pool_id is required in self-hosting

- spacelift/data_aws_integrations.go
- spacelift/data_aws_integrations_test.go
- spacelift/data_azure_integrations.go
- spacelift/data_azure_integrations_test.go
- spacelift/internal/testhelpers/helpers.go
This is a bugfix there `integration_id` is missing from the data sources. I've also added some helpers that help asserting nested attributes and checking lists of items for content
> Fix [#1]()
> Add integration_id to AWS, Azure integrations list

- docs/resources/environment_variable.md
- spacelift/resource_environment_variable.go
Clarify the purpose of the `write_only` argument of the `spacelift_environment_variable` resource type.
None
> Clarify the purpose of the `write_only` argument of the `spacelift_environment_variable` resource type

- docs/data-sources/ips.md
- spacelift/data_ips.go
Adding a note to the description of the `spacelift_ips` data source to make it more obvious that this doesn't include the IPs of the public worker pool, and to link to the docs on setting up private worker pools.
> Fix [#1]()
> Explain ips datasource doesn't include workers

- spacelift/data_space.go
- spacelift/resource_space.go
Customer is receiving the following error: `Planning failed. Terraform encountered an error while generating this plan. ╷ │ Error: space not found │ │ ╵`
Lets add the space ID to the error message to make troubleshooting easier.
> Add space ID to space not found error message

- main.go
This add support a `-debug` flag so we could enable debug mode. See [terraform doc](https://developer.hashicorp.com/terraform/plugin/debugging#enabling-debugging-in-a-provider) for more details.
That allows us to run the provider in debug mode, and make terraform attach a running provider using `TF_REATTACH_PROVIDERS `. Thus we could add breakpoints and debug the provider at runtime.
N/A
> feat: add debug flag

- .vscode/settings.json
- docs/data-sources/context.md
- docs/resources/context.md
- spacelift/data_context.go
- spacelift/data_context_test.go
- spacelift/internal/structs/context.go
- spacelift/internal/structs/context_input.go
- spacelift/resource_context.go
- spacelift/resource_context_test.go
> Introduce support for context hooks

- docs/data-sources/bitbucket_cloud_integration.md
- spacelift/data_bitbucket_cloud_integration.go
- spacelift/data_bitbucket_cloud_integration_test.go
Expose Bitbucket Cloud integration webhook URL.
> Add `webhook_url` to Bitbucket Cloud integration data source

- .github/workflows/release-beta.yml
A GH Action to allow us to publish beta versions of terraform provider manually.
> Enable releasing beta versions of provider

- spacelift/resource_aws_integration_attachment.go
- spacelift/resource_aws_role.go
We recently updated the error message returned from our server to help clarify to users of the spacelift UI what actions they need to take to resolve their issue. However we missed updating the retry loop here specifically checking for the text of the old error.
I will be making a comment internally too to ensure that any future changes to those error messages are also reflected here in the provider.
Fixes #493
> Use correct retry logic when handling AWS roles and their attatchments

- docs/data-sources/github_enterprise_integration.md
- spacelift/data_github_enterprise_integration.go
- spacelift/data_github_enterprise_integration_test.go
Azure DevOps, Bitbucket Cloud, Bitbucket Datacenter, and GitLab have `webhook_url,`, but GitHub hasn't. 
> Fix [#1]()
> Multi VCS - add missing webhook_url for GitHub (#477)

- docs/resources/space.md
- spacelift/resource_space.go
The `spacelift_space` resource requires root space admin permissions to work. This means that it can only be used by administrative stacks that live in the root space.
I've added a note to the provider docs to make that more obvious.
> docs: document root admin requirement for spacelift_space

- docs/data-sources/module.md
- docs/data-sources/stack.md
- docs/data-sources/stacks.md
- spacelift/data_module.go
- spacelift/data_stack.go
- spacelift/data_stacks.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/stack.go
- spacelift/resource_module.go
- spacelift/resource_stack.go
- We've added is_default into stack/module resource. We need to do the same with data sources as well.
- Prevent panic on detached VCS integration
> Fix [#1]()
> MultiVCS: Added is_default into stack/module data source and prevent panic on detached VCS integration

- docs/resources/run.md
- go.mod
- spacelift/internal/error.go
- spacelift/resource_run.go
- spacelift/resource_run_test.go
- spacelift/resource_stack_test.go
From [PR](https://github.com/spacelift-io/terraform-provider-spacelift/pull/522)
This PR contains an extension of the resource spacelift_run, which makes it possible to wait for the completion of a run.
> Fix [#1]()
>  feat: wait for run in resource `spacelift_run`

- spacelift/resource_stack_dependency_reference.go
If the stack or the dependency is removed manually, it will not be possible to delete stack dependency reference. Throughout the rest of the provider we use a consistent pattern of just removing these resources from the state, and not treating it as an error. We will emit a warning here in case anyone misses the old error messages, but otherwise let's have this resource behave like all other resources.
> Fix deleting non-existing stack dependency references

- docs/resources/version.md
- spacelift/resource_version.go
adds the word "module" to clarify this resource is specifically for modules as it can be confusing to (especially self hosted) customers when they see spacelift_version 
> Fix [#1]()
> adds word "module" to spacelift_version

- docs/resources/stack_dependency_reference.md
- spacelift/internal/structs/stack_dependency_reference.go
- spacelift/resource_stack_dependency_reference.go
- spacelift/resource_stack_dependency_reference_test.go
It's also backward compatible (false by default).
> Add `trigger_always` option to Stack Dependency References

- spacelift/data_aws_integration_attachment_test.go
- spacelift/data_aws_role_test.go
- spacelift/data_azure_integration_attachment_test.go
- spacelift/data_context_attachment_test.go
- spacelift/data_environment_variable_test.go
- spacelift/data_gcp_service_account_test.go
- spacelift/data_module_test.go
- spacelift/data_mounted_file_test.go
- spacelift/data_stack_test.go
- spacelift/data_webhook_test.go
- spacelift/resource_aws_role_test.go
- spacelift/resource_context_attachment_test.go
- spacelift/resource_environment_variable_test.go
- spacelift/resource_gcp_service_account_test.go
- spacelift/resource_module_test.go
- spacelift/resource_mounted_file_test.go
- spacelift/resource_policy_attachment_test.go
- spacelift/resource_stack_test.go
- spacelift/resource_webhook_test.go
> Update module id

- spacelift/internal/testhelpers/helpers.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
Let's reset the version when we're changing the terragrunt tool. 
Step 1 - now we have computed the latest for terraform (1.5.7)
```tf
resource spacelift_stack this {
...
terragrunt {
tool = "TERRAGRUNT_FOSS"
}
}
```
Step 2 - we expect the latest for opentofu (1.7.1)
```tf
resource spacelift_stack this {
...
terragrunt {
tool = "OPEN_TOFU"
}
}
```
Let's reset `terraform_version` when we're changing `tool` and `terraform_version` is not specified in the config.
Let's also take care of `terraform_workflow_tool`. It's the same situation. We should reset `terraform_version` in the case of the tool change.
```tf
resource spacelift_stack this {
...
terraform_workflow_tool = "TERRAFORM_FOSS"
...
}
```
into:
```tf
resource spacelift_stack this {
...
terraform_workflow_tool = "CUSTOM"
...
}
```
> …
> Terragrunt OpenTofu: reset terraform_version when changing tool

- docs/data-sources/module.md
- docs/resources/module.md
- spacelift/data_module.go
- spacelift/data_module_test.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/module_input.go
- spacelift/resource_module.go
- spacelift/resource_module_test.go
Add 'Raw Git' configuration block to modules.
> Add support for 'Raw Git' to modules

- docs/data-sources/environment_variable.md
- docs/resources/environment_variable.md
- examples/resources/spacelift_environment_variable/resource.tf
- spacelift/data_environment_variable.go
- spacelift/data_environment_variable_test.go
- spacelift/internal/structs/config_element.go
- spacelift/internal/structs/config_input.go
- spacelift/resource_environment_variable.go
- spacelift/resource_environment_variable_test.go
> Adding a new optional field to spacelift_environment_variable Terraform module called **description**, [more details](https://app.clickup.com/t/8695950mj).
> feat(env-vars): Add `description` field to Terraform spacelift_environment_variable resource

- spacelift/resource_audit_trail_webhook_test.go
We dont want to send requests to the this domain in tests, lets disable it 
> Fix [#1]()
> fix: disable audit webhook in tests

- spacelift/provider.go
Updated the code that builds the URL for the GraphQL API to handle the situation where the `api_key_endpoint` setting includes a trailing `/`.
This is the PR from @akmal-spacelift from [here](https://github.com/spacelift-io/terraform-provider-spacelift/pull/568).
> Fix [#1]()
> Handle slash at endpoint

- docs/data-sources/current_space.md
- spacelift/data_current_space.go
- spacelift/data_space.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/stack.go
Adds the same properties that `space` data source has to the `spacelift_current_space` data source.
> feat: add additional properties to the spacelift_current_space data source

- docs/resources/module.md
- spacelift/internal/structs/module.go
- spacelift/resource_module.go
- spacelift/resource_module_test.go
Allow creating public modules with Terraform
> feat: support creating public modules

- spacelift/resource_worker_pool.go
- spacelift/resource_worker_pool_test.go
It looks like theres no way to update the CSR after the workerpool has been created. We only set this value on create. We should force new resources if this value was to change. Its only comparing the CSR to state, so if someone was to update this today they'd think they made a change when they really didnt.
> fix: force new when the csr changes

- docs/resources/idp_group_mapping.md
- docs/resources/user.md
- spacelift/resource_idp_group_mapping.go
- spacelift/resource_user.go
- spacelift/resource_user_test.go
This is essentially @bushong1 's change, plus some additional fixes. Quoting:
https://github.com/spacelift-io/terraform-provider-spacelift/pull/577
> I’ve been having some trouble with the Spacelift Terraform provider when managing user access policies. Every time I add a new policy, Terraform tries to delete and recreate some of the existing ones—even though they haven’t changed at all. It’s like it’s getting confused about what’s actually new and what’s already there.
> I think the problem is with how the policy field is set up in the spacelift_user resource. Right now, it’s defined as a TypeList, which is ordered. So when I insert a new policy somewhere other than the end of the list, it shifts the order, and Terraform thinks the policies have changed.
> To fix this, I think we should …
> Convert user policies from `List` to `Set`

- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
We should not save peoples state to our state file. If an admin stack is managing many stacks with `import_state` it could cause peoples state to explode in size and it also causes memory to explode because of internal terraform comparisons. I have examples of this, if you'd like to see them.
Because of this attributes' `DiffSuppressFunc`, we will never see a change here so whats in state does not matter. I can also think of an easy way to allow diffing of this when using `ForceNew` as well, but I was unsure if this was purposefully added here since we're dealing with state so I left that alone. Happy to discuss that if warranted.
This change will:
1. Ensure that any new stacks created with `import_state` will not save the imported state to this state file.
2. Will migrate any existing …
> feat: do not save imported state to statefile

- docs/data-sources/stack.md
- docs/data-sources/stacks.md
- docs/resources/stack.md
- spacelift/data_stack.go
- spacelift/data_stack_test.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
Currently, users can only select custom workflow through the UI. A user has requested to be able to do it through the provider also. 
[Support custom workflow for kubernetes stack through terraform creation.](https://app.clickup.com/t/8694afyu7)
> feat: add `kubernete_workflow_tool` property to the kubernetes schema

- .github/workflows/check-documentation.yml
- .github/workflows/test-prod.yml
- .github/workflows/test.yml
Terraform binary has been removed from ubuntu-latest, so let's install
it in our pipeline.
I also pinned TF version used in all workflows to avoid surprises.
> Fix [#1]()
> fix: install TF on doc workflow

- spacelift/resource_context_test.go
Tests are broken because we merged a contributor PR (#591) bypassing tests.
> fix: tests

- spacelift/resource_aws_integration_attachment.go
- spacelift/resource_aws_integration_attachment_test.go
The problem is that the field used to store the response from the mutation wasn't exported, causing the `struct field for "awsIntegrationAttachmentUpdate" doesn't exist in any of 1 places to unmarshal` error.
Fixes #610
> fix: error when updating an AWS integration attachment

- spacelift/internal/client.go
Spacelict API returns somewhat inconsistent errors for not-found resources.
For some resources (like stacks), it returns null values in the results, but for other queries, it returns a "not found" error.
The problem is that we decide to recreate a resource if the response is null, but if it’s an error response, then we return an error to the end user.
This PR changes the error handling of the query method and returns an empty result on not found error.
> Fix [#1]()
> fix: ignore not found error

- docs/resources/worker_pool.md
- spacelift/resource_worker_pool.go
- spacelift/resource_worker_pool_test.go
With this change we allow decoratively resetting worker pool credentials. If the CSR changes, the token is recreated.
It's based on [this](https://github.com/spacelift-io/terraform-provider-spacelift/pull/630) PR with small fix and tests adjustments.
> feat: reset worker pools on csr update

- spacelift/internal/error.go
Making error message more informative.
> Fix [#1]()
> chore(errors): Improve error messaging for administrative stacks

- docs/data-sources/aws_role.md
- docs/data-sources/stack_aws_role.md
- docs/resources/aws_role.md
- docs/resources/stack_aws_role.md
- spacelift/data_aws_role.go
- spacelift/data_aws_role_test.go
- spacelift/internal/structs/integrations.go
- spacelift/resource_aws_role.go
- spacelift/resource_aws_role_test.go
Adds region to `spacelift_aws_role` resource and data source.
> Fix [#1]()
> Add region to AWS role resource and data source

- README.md
- spacelift/internal/structs/stack.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
Fixes https://github.com/spacelift-io/terraform-provider-spacelift/issues/647
> fix: allow to nullify `terraform_version` on the stack resource

- docs/data-sources/worker_pool.md
- docs/data-sources/worker_pools.md
- docs/resources/worker_pool.md
- examples/resources/spacelift_worker_pool/resource.tf
- spacelift/data_worker_pool.go
- spacelift/data_worker_pool_test.go
- spacelift/data_worker_pools.go
- spacelift/data_worker_pools_test.go
- spacelift/internal/structs/worker_pool.go
- spacelift/resource_worker_pool.go
- spacelift/resource_worker_pool_test.go
This change adds a new optional field to configure the maximum number of concurrent drift detection runs allowed per worker pool. The field uses -1 as a default value which the server interprets as "unset", allowing users to explicitly set limits including 0 to disable drift detection entirely.
* Add drift_detection_run_limit field to worker pool resource and data sources
* Set default value of -1 (interpreted as unset by server)
* Support explicit values including 0 to disable drift detection
* Add GraphQL integration with driftDetectionRunLimit parameter
> feat: add drift_detection_run_limit field to worker pool

- spacelift/data_module_test.go
- spacelift/resource_module_test.go
Upcoming changes will validate for account names when saving module shares, so those tests will error soon if we do not change them to use an account that actually exist.
> fix: test for new module sharing

- docs/data-sources/named_webhook.md
- docs/data-sources/webhook.md
- docs/resources/audit_trail_webhook.md
- docs/resources/named_webhook.md
- docs/resources/webhook.md
- spacelift/data_named_webhook.go
- spacelift/data_named_webhook_test.go
- spacelift/data_webhook.go
- spacelift/data_webhook_test.go
- spacelift/internal/structs/audit_trail_webhook.go
- spacelift/internal/structs/audit_trail_webhook_input.go
- spacelift/internal/structs/integrations.go
- spacelift/internal/structs/named_webhook_input.go
- spacelift/internal/structs/webhook_input.go
- spacelift/resource_audit_trail_webhook.go
- spacelift/resource_audit_trail_webhook_test.go
- spacelift/resource_named_webhook.go
- spacelift/resource_named_webhook_test.go
- spacelift/resource_webhook.go
- spacelift/resource_webhook_test.go
We've recently added this as a setting to all webhooks, so I'm not also extending the provider.
> Fix [#1]()
> Allow to set the retry setting in all webhooks

- docs/resources/saved_filter.md
- spacelift/resource_saved_filter.go
A few were missing from the list.
Fixes https://github.com/spacelift-io/terraform-provider-spacelift/issues/638
> docs(saved-filters): extend docs with a few more saved filter types
