- Dockerfile
Reverts spacelift-io/terraform-provider-spacelift#38
> Revert "Provider symlink for 0.13"

- go.mod
- go.sum
- spacelift/resource_context.go
- spacelift/resource_policy.go
- spacelift/resource_stack.go
- spacelift/resource_stack_aws_role.go
- spacelift/resource_stack_webhook.go
- spacelift/resource_worker_pool.go
This reverts commit 19100b535062238ae4e47bcf58d4b883736ed9fd.
> Revert "Fix unsuccessful updates and state (#57)"

- .github/pull_request_template.md
Add documentation as type of change to pull request template
> Add documentation as type of change to pull request template

- README.md
> Add Pulumi documentation.

- README.md
Adds documentation for the worker pools data source.
> Add worker pools data source documentation

- .github/pull_request_template.md
- README.md
> Bring in future changes

- README.md
- spacelift/data_stack.go
- spacelift/data_stack_test.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
This change adds support for setting Terraform workspace, and factors out Terraform settings into a separate block (optional for now).
> Add Terraform workspace support

- spacelift/resource_stack.go
If the Terraform version is set on the stack, it should not be updated by an unset version in the config.
> Mark Terraform version as computed

- README.md
- spacelift/data_stack.go
- spacelift/data_stack_test.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Merge future changes

- README.md
- spacelift/data_stack.go
- spacelift/data_stack_test.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Support setting and reading before apply hooks

- README.md
- spacelift/data_aws_role.go
- spacelift/data_aws_role_test.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/stack.go
- spacelift/resource_aws_role.go
- spacelift/resource_aws_role_test.go
> Generating AWS credentials in the private worker

- spacelift/resource_context_attachment.go
- spacelift/resource_policy_attachment.go
After we introduced the concept of modules, we accidentally broke importing both policy and context attachments. This is because apart from the ID, a successful "read" now needs to know whether the attached entity is a stack or a module. This change fixes the problem as well as introduces new logic that allows one to import attachments without having to know the attachment ID up front - just the context/policy ID and the stack/module ID.
> Fix attachment imports

- README.md
- spacelift/integration_importer.go
- spacelift/internal/structs/integrations.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/stack.go
- spacelift/resource_aws_role.go
- spacelift/resource_aws_role_test.go
- spacelift/resource_context_attachment_test.go
- spacelift/resource_context_test.go
- spacelift/resource_environment_variable.go
- spacelift/resource_environment_variable_test.go
- spacelift/resource_gcp_service_account.go
- spacelift/resource_gcp_service_account_test.go
- spacelift/resource_module_test.go
- spacelift/resource_mounted_file.go
- spacelift/resource_mounted_file_test.go
- spacelift/resource_policy_attachment.go
- spacelift/resource_policy_attachment_test.go
- spacelift/resource_policy_test.go
- spacelift/resource_stack_test.go
- spacelift/resource_webhook.go
- spacelift/resource_webhook_test.go
- spacelift/resource_worker_pool.go
- spacelift/resource_worker_pool_test.go
The introduction of modules broke quite a few imports. These are fixed now, and tests have been added for future regressions. In addition, documentation for each resource now contains a section on how to import it to the Terraform state.
> Test (and fix) imports for all resources

- Dockerfile
> Bump Alpine and builder image

- Dockerfile
> Release future changes

- README.md
- spacelift/data_aws_role.go
- spacelift/data_aws_role_test.go
- spacelift/internal/structs/integrations.go
- spacelift/resource_aws_role.go
- spacelift/resource_aws_role_test.go
> Support custom AWS external ID for private workers

- README.md
Format Terraform provider configuration.
Remove extra space.
> Format Terraform provider configuration

- .github/workflows/deploy.yml
- README.md
Push to registry with timestamp tag
> Push to registry with timestamp tag

- .github/workflows/deploy.yml
- README.md
- spacelift/data_aws_role.go
- spacelift/data_aws_role_test.go
- spacelift/internal/structs/integrations.go
- spacelift/resource_aws_role.go
- spacelift/resource_aws_role_test.go
> Merge in future changes

- spacelift/internal/structs/stack.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Wait for destroy

- .github/workflows/analysis-codeql.yml
- .github/workflows/analysis-gosec.yml
- .github/workflows/analysis-trivy.yml
- spacelift/internal/structs/stack.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Merge to pro

- README.md
- spacelift/resource_stack.go
> Add wait_for_destroy docs.

- Dockerfile
Let's add Terragrunt to our standard Terraform runner image, in anticipation of upcoming Terragrunt support
> Add Terragrunt

- Dockerfile
> Add Terragrunt (#135)

- README.md
- spacelift/provider.go
- spacelift/resource_stack.go
- spacelift/resource_stack_destructor.go
- spacelift/resource_stack_test.go
> Add Stack Destructor

- .github/workflows/deploy.yml
> Deploy runner image to public ECR

- Dockerfile
- README.md
> Documentation update.

- Dockerfile
- README.md
* Documentation update.
* Update README.md
* Update Dockerfile
> Fix [#1]()
> Merge to prod

- Dockerfile
> Add Infracost binary

- Dockerfile
- README.md
- spacelift/resource_policy_attachment.go
- spacelift/resource_policy_attachment_test.go
> Pull in future changes

- spacelift/internal/structs/policy_attachment.go
> Do not query for custom policy input

- spacelift/internal/structs/policy_attachment.go
> Do not query for custom policy input (#145)

- .github/workflows/test.yml
> Goodbye, codecov

- .github/workflows/deploy.yml
- .github/workflows/registry.yml
- .github/workflows/test.yml
> Deploy from self-hosted workers

- spacelift/data_current_stack.go
> Fix unverified error comparison

- spacelift/provider.go
> Fix audience validation

- .github/workflows/registry-preprod.yml
- .github/workflows/registry-prod.yml
> Remove dryrun mode, fix path invalidation

- README.md
- spacelift/data_context.go
- spacelift/data_context_test.go
- spacelift/data_policy.go
- spacelift/data_policy_test.go
- spacelift/internal/structs/context.go
- spacelift/internal/structs/policy.go
- spacelift/resource_context.go
- spacelift/resource_context_test.go
- spacelift/resource_policy.go
- spacelift/resource_policy_test.go
> Support labels in contexts and policies

- .github/workflows/registry-prod.yml
> Fix provider domain for prod deployment

- spacelift/internal/error.go
- spacelift/resource_context.go
- spacelift/resource_context_attachment.go
- spacelift/resource_environment_variable.go
- spacelift/resource_module.go
- spacelift/resource_mounted_file.go
- spacelift/resource_policy.go
- spacelift/resource_policy_attachment.go
- spacelift/resource_stack.go
- spacelift/resource_stack_destructor.go
- spacelift/resource_webhook.go
- spacelift/resource_worker_pool.go
Add clear error for non-administrative stacks
> Add clear error for non-administrative stacks

- go.sum
- spacelift/data_stack.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Add local preview stack setting

- spacelift/data_stack.go
- spacelift/resource_stack.go
> Add showcases support.

- README.md
> Point folks to Hashi registry

- spacelift/data_module.go
- spacelift/data_module_test.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/module_input.go
- spacelift/internal/testhelpers/helpers.go
- spacelift/resource_module.go
- spacelift/resource_module_test.go
> Support better modules

- spacelift/provider.go
- spacelift/resource_run.go
- spacelift/resource_run_test.go
This PR adds the ability to trigger a tracked run declaratively.
> Run resource

- Dockerfile
> Update Infracost to 0.8.7

- Dockerfile
> Install jq and update Infracost to 0.9.1

- spacelift/resource_stack_destructor.go
> Extend destruction timeout to 2h.

- Dockerfile
> Release latest runner image changes

- spacelift/data_stack.go
- spacelift/data_stack_test.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Add before and after stack hooks (#195)

- Dockerfile
> Update Infracost to 0.9.4

- docs/data-sources/stack.md
- docs/resources/stack.md
> Add docs for hooks

- Dockerfile
- docs/data-sources/stack.md
- docs/resources/stack.md
Merge future into master to deploy latest changes (Infracost update and docs for hooks).
> Merge future to master

- Dockerfile
Release notes: https://github.com/infracost/infracost/releases/tag/v0.9.5
> Update Infracost to 0.9.5

- Dockerfile
Releasing the Infracost upgrade.
> Merge future into master

- .github/workflows/test.yml
- Dockerfile
> Bump Infracost

- docs/resources/run.md
- spacelift/resource_run.go
> Allow spacelift_run to create proposed runs

- docs/resources/policy.md
Minor change to the documentation.
> Fix [#1]()
> Added missing quote to policy documentation

- Dockerfile
Merging latest changes from master into future.
> Merge master into future

- Dockerfile
> Update Infracost to v0.9.13

- docs/data-sources/module.md
- docs/data-sources/stack.md
- docs/resources/module.md
- docs/resources/stack.md
- spacelift/data_module.go
- spacelift/data_stack.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/module_input.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_module.go
- spacelift/resource_module_test.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Backend-driven deletion protection

- docs/data-sources/module.md
- docs/data-sources/stack.md
- docs/data-sources/worker_pool.md
- docs/resources/azure_integration_attachment.md
- docs/resources/module.md
- docs/resources/stack.md
- docs/resources/worker_pool.md
- spacelift/data_module.go
- spacelift/data_stack.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/vcs_provider.go
- spacelift/resource_module.go
- spacelift/resource_stack.go
- spacelift/vcs_provider.go
> Support Azure DevOps VCS provider + minor refactor

- docs/data-sources/module.md
- docs/data-sources/stack.md
- docs/data-sources/worker_pool.md
- docs/resources/azure_integration_attachment.md
- docs/resources/module.md
- docs/resources/stack.md
- docs/resources/worker_pool.md
- spacelift/data_module.go
- spacelift/data_stack.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/vcs_provider.go
- spacelift/resource_module.go
- spacelift/resource_stack.go
- spacelift/vcs_provider.go
Changes:
- importing state files by path;
- support for stacks using Azure DevOps as their VCS;
Closes #252
> Sync future changes

- spacelift/internal/client.go
> Add HTTP client timeout

- spacelift/resource_policy.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Replace POST with PUT for uploading state

- .github/workflows/build-package.yml
- .github/workflows/registry-prod.yml
> Replace AWS static credentials with GitHub OIDC

- .github/workflows/registry-preprod.yml
- .github/workflows/registry-prod.yml
> Fix OIDC permissions

- spacelift/resource_context_attachment.go
Clarify how the values for the `priority` attribute of the `spacelift_context_attachment` resource type are used.
None
> Improve spacelift_context_attachment.priority documentation

- spacelift/resource_aws_role.go
> Fix AWS role retry

- .github/workflows/analysis-codeql.yml
- .github/workflows/analysis-gosec.yml
- .github/workflows/build-package.yml
- .github/workflows/registry-prod.yml
- .github/workflows/test-prod.yml
> Switch to main as the default branch

- .github/prod_deployment_template.md
- .github/workflows/production-deployment-pull_request.yml
Added a workflow to automatically create a PR when there are changes in future that need to be merged into main.
> Create production deploy PR

- docs/data-sources/policies.md
- examples/data-sources/spacelift_policies/data-source.tf
The example was a bit misleading since it would output the ID of the `spacelift_policies` data source, rather than the list of policy IDs.
> Fix policies data source example

- spacelift/data_aws_role.go
- spacelift/data_aws_role_test.go
- spacelift/internal/structs/integrations.go
- spacelift/resource_aws_role.go
- spacelift/resource_aws_role_test.go
- spacelift/type_conversions.go
Introducing duraction_seconds for aws role.
> specify aws role duration seconds for aws role

- docs/data-sources/aws_role.md
- docs/data-sources/stack_aws_role.md
- docs/resources/aws_role.md
- docs/resources/stack_aws_role.md
> Update docs after adding duration seconds to aws role

- .github/pull_request_template.md
> Mention `tfplugindocs` in PR template

- README.md
> Add information about using a local build of the provider

- .github/workflows/build-package.yml
- .github/workflows/registry-preprod.yml
- .github/workflows/registry-prod.yml
- .github/workflows/test-prod.yml
- .github/workflows/test.yml
- .github/workflows/tfpackage.yml
- .golangci.yml
- README.md
- docs/resources/stack.md
- spacelift/data_account.go
- spacelift/data_aws_role.go
- spacelift/data_gcp_service_account.go
- spacelift/resource_aws_role.go
- spacelift/resource_environment_variable.go
- spacelift/resource_gcp_service_account.go
- spacelift/resource_mounted_file.go
Bumping the Go version to 1.18.
> Fix [#1]()
> Bumping build process to Go 1.18

- docs/resources/aws_role.md
- docs/resources/azure_integration_attachment.md
- docs/resources/context_attachment.md
- docs/resources/drift_detection.md
- docs/resources/environment_variable.md
- docs/resources/module.md
- docs/resources/mounted_file.md
- docs/resources/run.md
- docs/resources/stack.md
- docs/resources/stack_aws_role.md
- docs/resources/webhook.md
- spacelift/resource_aws_role.go
- spacelift/resource_azure_integration_attachment.go
- spacelift/resource_context_attachment.go
- spacelift/resource_drift_detection.go
- spacelift/resource_environment_variable.go
- spacelift/resource_module.go
- spacelift/resource_mounted_file.go
- spacelift/resource_run.go
- spacelift/resource_stack.go
- spacelift/resource_webhook.go
> Document default values

- spacelift/resource_stack.go
Previously if someone tried to import a stack, and included the `slug` attribute, Terraform would force a recreate on the next apply because we didn't import `slug` into the state (so it detected a change from null to the actual value).
I've added a custom importer that just reads the stack information using the existing stack read function. I've also marked the slug as computed - this means that if an existing stack resource doesn't specify the slug, it won't force a recreate.
- Fixes #315
> Mark slug as computed and import to state

- .github/pull_request_template.md
- docs/resources/aws_integration.md
- docs/resources/aws_integration_attachment.md
- docs/resources/space.md
- spacelift/resource_aws_integration.go
- spacelift/resource_aws_integration_attachment.go
- spacelift/resource_space.go
This PR adds missing documentation for default values for some newly introduced resource types.
It also adds a check in the PR template to remind developers to document default values.
None
> Add missing documentation for default values

- spacelift/resource_drift_detection.go
Add check if drift detection exists when reading resource
> Add check if drift detection exists when reading resource

- .github/pull_request_template.md
- .github/workflows/check-documentation.yml
> Add action to check if documentation has changed

- .github/workflows/check-documentation.yml
This is minor fix for #338. This PR only updates the recommended command to generate the documentation to reflect the new workflow. 
None
> Fix command to generate documentation

- docs/resources/stack_destructor.md
- spacelift/resource_stack_destructor.go
> Fix spelling error

- .github/workflows/analysis-codeql.yml
> Upgrade CodeQL Action

- docs/data-sources/aws_integration.md
- docs/resources/aws_integration.md
- spacelift/data_aws_integration.go
- spacelift/resource_aws_integration.go
We actually tweaked the format to always use `@` signs instead of using `-` to separate the components.
> Fix external ID format for AWS integration

- docs/resources/stack_dependency.md
- spacelift/resource_stack_dependency.go
Add notice to stack deps
> Fix [#1]()
> Add notice to stack dependencies, as it's not ready yet

- docs/resources/stack.md
- spacelift/resource_stack.go
Clarify the purpose of the `spacelift_stack.github_enterprise` argument.
This is a temporary measure to avoid too much confusion until we rename the argument.
_None_
> Clarify the purpose of the github_enterprise argument

- docs/resources/stack.md
- examples/resources/spacelift_stack/resource.tf
Bump Terraform version number in examples
_None_
> Bump Terraform version number in examples

- spacelift/resource_policy.go
> Support changing policy name

- spacelift/internal/structs/module_input.go
- spacelift/resource_module.go
> Add support for changing module source

- docs/data-sources/space.md
- docs/resources/space.md
- spacelift/data_space.go
- spacelift/data_space_test.go
- spacelift/internal/structs/space.go
- spacelift/resource_space.go
- spacelift/resource_space_test.go
Support in the API is there, let's expose it in the provider.
> Add support for labels in spaces

- .github/workflows/test.yml
I hope this fixes the panic after 10 minutes in tests
> Fix [#1]()
> Double test timeout

- docs/resources/stack_dependency.md
- spacelift/resource_stack_dependency.go
> Remove stack dependencies warning

- .github/workflows/tfpackage.yml
> Release to our own private TF registry

- .github/workflows/tfpackage.yml
> Change key importer

- README.md
> Change release procedure in README

- .github/workflows/release.yml
- .github/workflows/test-prod.yml
> Update secrets for testing terraform provider for production

- docs/resources/stack.md
- spacelift/resource_stack.go
Add default space ID for the spacelift_stack resource
None
> Add default space ID for the spacelift_stack resource

- spacelift/data_stacks.go
> Populate labels for spacelift_stacks data source

- spacelift/resource_scheduled_delete_stack.go
- spacelift/resource_scheduled_task.go
- spacelift/resource_stack_dependency.go
> Stack dependency can be missing on read

- .goreleaser.yml
- spacelift/resource_blueprint.go
- spacelift/resource_blueprint_test.go
> Blueprint: updating templatebody forces recreation

- .github/workflows/test-prod.yml
> Prod tests longer timeout

- spacelift/data_contexts_test.go
The selector will now be unique to the test execution.
> Deflake contexts data source test

- docs/resources/stack.md
- spacelift/internal/structs/stack_input.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Add use_smart_sanitization to terragunt configs

- docs/data-sources/stack.md
- docs/data-sources/stacks.md
- docs/resources/stack.md
- spacelift/data_stack.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/internal/structs/vcs_provider.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Add support for the raw Git link VCS provider

- README.md
[
> Description here](fix: small typo in readme)
> fix: small typo in readme

- README.md
Fix release wiki URL in readme
> fix: outdated release wiki URL

- .github/workflows/analysis-codeql.yml
- .github/workflows/analysis-gosec.yml
- .github/workflows/analysis-lint.yml
- .github/workflows/check-documentation.yml
- .github/workflows/release.yml
- .github/workflows/test-prod.yml
- .github/workflows/test.yml
- spacelift/internal/structs/stack.go
- spacelift/resource_stack_dependency_reference.go
> Add better error message for Stack Dependency References

- spacelift/data_module.go
- spacelift/data_stack.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/stack.go
- spacelift/resource_module.go
Remove unneccessary VCS properties #487
> Remove unneccessary VCS properties

- spacelift/resource_module.go
- spacelift/resource_stack.go
Strange behavior.
> Fix [#1]()
> Extend nil checks

- docs/resources/module.md
- docs/resources/stack.md
- spacelift/internal/structs/module.go
- spacelift/internal/structs/stack.go
- spacelift/resource_module.go
- spacelift/resource_module_test.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
> Check is_default when calculating diff for stacks and modules VCS setting

- spacelift/resource_module.go
- spacelift/resource_stack.go
Without computed for VCS integration id, too many changed at once
> Fix [#1]()
> without computed for VCS integration id , too many changed at once

- docs/resources/user.md
- spacelift/internal/structs/user_input.go
- spacelift/resource_user.go
- spacelift/resource_user_test.go
- Make invitation email optional
- Handle invitation email being not provided during create
> Handle import for users with no invitation email

- docs/resources/stack.md
- spacelift/resource_stack.go
Remove the reference to GitHub in the stack branch argument documentation
None
> Remove the reference to GitHub in the stack branch argument documentation

- spacelift/resource_stack_test.go
Backend does not allow it anymore. One of the tests used this feature so we need to refactor it.
> fix: changing vendor for a stack is no longer allowed

- spacelift/resource_context.go
- spacelift/resource_context_test.go
See https://github.com/spacelift-io/terraform-provider-spacelift/issues/578
> Fixes https://github.com/spacelift-io/terraform-provider-spacelift/issues/578
> Don't recreate contexts on rename

- docs/resources/mounted_file.md
- spacelift/resource_mounted_file.go
- spacelift/resource_mounted_file_test.go
Resolving https://github.com/spacelift-io/terraform-provider-spacelift/issues/603
> Add description to `spacelift_mounted_file`

- README.md
> Add opentofu registry documentation link

- docs/resources/idp_group_mapping.md
- examples/resources/spacelift_idp_group_mapping/resource.tf
- spacelift/internal/structs/user_group.go
- spacelift/internal/structs/user_group_input.go
- spacelift/resource_idp_group_mapping.go
- spacelift/resource_idp_group_mapping_test.go
Follow up to recent API extension
> Fix [#1]()
> UserGroup description

- docs/data-sources/module.md
- docs/data-sources/stack.md
- docs/data-sources/stacks.md
- docs/resources/module.md
- docs/resources/stack.md
- spacelift/data_module.go
- spacelift/data_module_test.go
- spacelift/data_stack.go
- spacelift/data_stack_test.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/module_input.go
- spacelift/internal/structs/stack.go
- spacelift/internal/structs/stack_input.go
- spacelift/resource_module.go
- spacelift/resource_module_test.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
Allow to pass sparse checkout paths in stack and module resource
> Fix [#1]()
> feat: Allow to define sparse checkout paths

- docs/data-sources/module.md
- docs/resources/module.md
- spacelift/data_module.go
- spacelift/internal/structs/module.go
- spacelift/internal/structs/module_input.go
- spacelift/resource_module.go
- spacelift/resource_module_test.go
> Add runner_image to module data source and resource

- docs/resources/stack.md
- spacelift/internal/structs/stack.go
- spacelift/resource_stack.go
- spacelift/resource_stack_test.go
Fixes https://github.com/spacelift-io/terraform-provider-spacelift/issues/608
> refactor: rename poorly named stack parameter
